### PR TITLE
Add extra fields to countToken response

### PR DESCRIPTION
**Pull request by cynthiajoan**

### CODE REVIEW

**Comment by lrhn** [comment]
I don't particularly understand the underlying protocol, but it seems the goal of hese classes are to not expose the JSON used for communication, so exposing it partially here doesn't seem consistent.

Do we know which properties the JSON object can have? Is it open-ended, or could we just define properties for every one of them, matching the incoming data?

**Comment by natebosch** [comment]
> Do we know which properties the JSON object can have? Is it open-ended, or could we just define properties for every one of them, matching the incoming data?

We do, but this package isn't the right place to record them.

We are currently using the same API classes between vertex AI and google AI, but the proto definitions for each are not the same source. The two APIs use _nearly_ identical protos, with _nearly_ identical JSON representation, but there can be slight variation.

**Comment by natebosch** [comment]
We discussed this off-thread.

I think for now we'll go with an approach like this with a few tweaks:
- We'll make the field private and expose it through an extension member which we won't make package public.
- We'll remove any fields we know about from the value, so that it retains only the unknown vertex-only fields.

I'll work on getting a PR up soon.

**Comment by lrhn** [comment]
Doesn't even have to be an extension member. That's almost too ergonomic.
Can be just a top-level function:
```dart
Map<String, Object?>? countTokensExtraJson(CountTokensResponse response) => response._extraJson;
```

**Comment by natebosch** [comment]
> Does the extra data have to be exposed by the constructor, or can we just set it internally in `fromJson` (using a private constructor, so the public constructor can only create objects with `null` extra data?
> Otherwise we are still exposing _something_ in the public API.

I think we should be able to set it in a private constructor as long as we also expose a way to access that constructor from vertex (mainly for testing).

**Comment by natebosch** [comment]
Landed in #153

**Pull request closed without merging**
