### PR TITLE
Add responseMimeType to GenerationConfig

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
I tested this manually and the model does respond with JSON so the implementation is correct, but I can't find a prompt that actually gets the model to reply with _useful_ JSON.

**Review by devoncarew — APPROVED** [review]
This is great!

Separately, I wonder where best to surface information about API features that are available? Should we have a 'how-to' section in the package's readme? Or, add a small additional API sample in the readme showing json output?

We could punt this entirely out of the packages's purvue and have complete docs on https://ai.google.dev/gemini-api/docs/api-overview#dart-flutter ? Do we have good reference from this package to those docs?

**Comment by natebosch** [comment]
Turns out the secret is _not_ putting a JSON formatted JSON schema into the text prompt. A prompt like this seems to work:

```
I want color schemes that contain 5 colours and a catchy name for each one. One for sunrise at Mount Fuji, one for Sunset in Hawaii, and one for midday in Jakarta. Use `name` and `colors` as the keys.
```

The "use `name` and `colors` as the keys`" seems to be enough.

Future work should add explicit support for a schema.

**Comment by natebosch** [comment]
> Do we have good reference from this package to those docs?

We didn't. I'll add one in the README in this change.

**Pull request merged**
